/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth2.glb -T 
Files: earth2.glb [8.55MB] > D:\cources\github\ThreeJs\portfolio\public\earth2-transformed.glb [137.61KB] (98%)
Author: ABOD.ANIMATION (https://sketchfab.com/body3d2005)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-c2e4294c32ea4d8b850e152fc26aeeb4
Title: earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earth2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, -0.262]} />
    </group>
  )
}

useGLTF.preload('/earth2-transformed.glb')
